package bashgen

import (
	"fmt"
	"path/filepath"
	"strings"

	"bashfs/internal/fswalker"
)

// GenerateDevMode produces bash code that references real files on disk.
// The returned code defines bashfs_cat, bashfs_extract, bashfs_list, and bashfs_jq functions.
func GenerateDevMode(files []fswalker.FileEntry, baseDir string) (string, error) {
	absDir, err := filepath.Abs(baseDir)
	if err != nil {
		return "", fmt.Errorf("resolving base directory: %w", err)
	}

	var b strings.Builder
	b.WriteString("# Generated by bashfs (dev mode) - DO NOT EDIT\n")
	fmt.Fprintf(&b, "# Source directory: %s\n\n", absDir)

	fmt.Fprintf(&b, `bashfs_cat() {
  local _bashfs_file="%s/$1"
  if [ ! -f "$_bashfs_file" ]; then
    echo "bashfs: file not found: $1" >&2
    return 1
  fi
  cat "$_bashfs_file"
}
`, absDir)

	b.WriteString("\n")

	fmt.Fprintf(&b, `bashfs_extract() {
  local _bashfs_file="%s/$1"
  local _bashfs_dest="$2"
  if [ ! -f "$_bashfs_file" ]; then
    echo "bashfs: file not found: $1" >&2
    return 1
  fi
  mkdir -p "$(dirname "$_bashfs_dest")" && cp "$_bashfs_file" "$_bashfs_dest"
}
`, absDir)

	b.WriteString("\n")

	b.WriteString("bashfs_list() {\n")
	for _, f := range files {
		fmt.Fprintf(&b, "  echo '%s'\n", f.RelPath)
	}
	b.WriteString("}\n")

	b.WriteString("\n")

	fmt.Fprintf(&b, `bashfs_jq() {
  local _bashfs_file="%s/$1"
  if [ ! -f "$_bashfs_file" ]; then
    echo "bashfs: file not found: $1" >&2
    return 1
  fi
  jq "${2:-.}" "$_bashfs_file"
}
`, absDir)

	return b.String(), nil
}
