package bashgen

import (
	"fmt"
	"os"
	"strings"

	"bashfs/internal/embed"
	"bashfs/internal/fswalker"
)

// EmbeddedResult holds the generated bash code and the trailing payload that
// gets appended to the script after the exit guard. For raw mode the payload
// is concatenated gzip bytes; for base64 mode it is a concatenation of
// per-file base64-encoded gzip chunks (still []byte, but printable ASCII).
type EmbeddedResult struct {
	Script  string
	Payload []byte
}

type fileInfo struct {
	relPath string
	offset  int
	length  int
}

// chunkFn turns a single file's raw contents into the bytes that get appended
// to the trailing payload.
type chunkFn func(data []byte) ([]byte, error)

// encodingSpec is everything that differs between raw and base64 modes. The
// generator pipeline is otherwise shared verbatim.
type encodingSpec struct {
	label  string  // appears in the header comment
	chunk  chunkFn // per-file payload transform
	decode string  // bash decode pipeline tacked on after `head -c "$_len" |`
}

var rawSpec = encodingSpec{
	label:  "embedded",
	chunk:  embed.Compress,
	decode: "gzip -d",
}

var base64Spec = encodingSpec{
	label: "base64",
	chunk: func(data []byte) ([]byte, error) {
		s, err := embed.Encode(data)
		if err != nil {
			return nil, err
		}
		return []byte(s), nil
	},
	decode: "base64 -d | gzip -d",
}

// GenerateEmbedded produces bash code that reads compressed file data from the
// end of the script itself (after an exit 0 guard). File contents are stored as
// a raw binary payload appended to the script; the bash code uses tail/head to
// extract individual files by byte offset and length.
func GenerateEmbedded(files []fswalker.FileEntry) (*EmbeddedResult, error) {
	return generate(files, rawSpec)
}

// GenerateEmbeddedBase64 is the copy-paste-safe variant: each file is gzipped
// then base64-encoded individually, and the per-file base64 chunks are
// concatenated as the trailing payload. Offsets in the map index the base64
// byte stream, so the runtime can slice a single file's chunk and decode just
// that chunk - no need to base64-decode the whole payload to extract one file.
//
// Per-file (rather than whole-payload) base64 encoding is what makes slicing
// safe: each chunk has its own padding and starts at a 4-byte boundary in the
// concatenated stream, so any sliced range is valid base64 standing alone.
func GenerateEmbeddedBase64(files []fswalker.FileEntry) (*EmbeddedResult, error) {
	return generate(files, base64Spec)
}

func generate(files []fswalker.FileEntry, spec encodingSpec) (*EmbeddedResult, error) {
	payload, infos, err := collectChunks(files, spec.chunk)
	if err != nil {
		return nil, err
	}

	checksum := embed.Checksum(payload)

	var b strings.Builder
	writePreamble(&b, spec.label, len(payload), checksum, infos)
	writeVerify(&b)
	writeExtractFns(&b, spec.decode)
	writeListAndJq(&b, infos)

	return &EmbeddedResult{
		Script:  b.String(),
		Payload: payload,
	}, nil
}

// collectChunks reads each file, transforms it via fn, and accumulates the
// transformed bytes into a single payload while tracking offsets/lengths into
// that payload.
func collectChunks(files []fswalker.FileEntry, fn chunkFn) ([]byte, []fileInfo, error) {
	var payload []byte
	var infos []fileInfo
	for _, f := range files {
		data, err := os.ReadFile(f.AbsPath)
		if err != nil {
			return nil, nil, fmt.Errorf("reading %s: %w", f.AbsPath, err)
		}
		chunk, err := fn(data)
		if err != nil {
			return nil, nil, fmt.Errorf("encoding %s: %w", f.RelPath, err)
		}
		infos = append(infos, fileInfo{
			relPath: f.RelPath,
			offset:  len(payload),
			length:  len(chunk),
		})
		payload = append(payload, chunk...)
	}
	return payload, infos, nil
}

// writePreamble emits the header comment, payload size, offset map, and
// __bashfs_payload_start helper.
func writePreamble(b *strings.Builder, modeLabel string, payloadSize int, checksum string, infos []fileInfo) {
	fmt.Fprintf(b, "# Generated by bashfs (%s mode) - DO NOT EDIT\n\n", modeLabel)

	fmt.Fprintf(b, "__bashfs_payload_size=%d\n", payloadSize)
	fmt.Fprintf(b, "__bashfs_payload_sha256=\"%s\"\n", checksum)
	fmt.Fprintf(b, "__bashfs_verified=0\n\n")

	b.WriteString("declare -A __bashfs_offset=(\n")
	for _, info := range infos {
		fmt.Fprintf(b, "  [\"%s\"]=\"%d:%d\"\n", info.relPath, info.offset, info.length)
	}
	b.WriteString(")\n\n")

	b.WriteString(`__bashfs_payload_start() {
  echo $(( $(wc -c < "${BASH_SOURCE[0]}") - __bashfs_payload_size + 1 ))
}

`)
}

const verifyTemplate = `bashfs_verify() {
  if [ "$__bashfs_payload_size" -eq 0 ]; then
    __bashfs_verified=1
    return 0
  fi
  local _actual
  _actual=$(tail -c "$__bashfs_payload_size" "${BASH_SOURCE[0]}" | sha256sum | cut -d' ' -f1)
  if [ "$_actual" != "$__bashfs_payload_sha256" ]; then
    echo "bashfs: payload integrity check failed (corrupted or truncated)" >&2
    echo "bashfs: expected sha256: $__bashfs_payload_sha256" >&2
    echo "bashfs: actual sha256:   $_actual" >&2
    return 1
  fi
  __bashfs_verified=1
}

`

func writeVerify(b *strings.Builder) {
	b.WriteString(verifyTemplate)
}

// extractTemplate is the bashfs_cat / bashfs_extract pair. The only thing that
// varies between encodings is the decode pipeline appended after the byte
// slice - substituted via the __DECODE__ placeholder. We can't use Go format
// strings here because the bash already contains literal % characters
// (${_info%%:*} and ${_info##*:}) that fmt.Sprintf would mangle.
const extractTemplate = `bashfs_cat() {
  if [ "$__bashfs_verified" -eq 0 ]; then
    bashfs_verify || return 1
  fi
  local _info="${__bashfs_offset[$1]}"
  if [ -z "$_info" ]; then
    echo "bashfs: file not found: $1" >&2
    return 1
  fi
  local _off="${_info%%:*}"
  local _len="${_info##*:}"
  tail -c "+$(($(__bashfs_payload_start) + _off))" "${BASH_SOURCE[0]}" | head -c "$_len" | __DECODE__
}

bashfs_extract() {
  if [ "$__bashfs_verified" -eq 0 ]; then
    bashfs_verify || return 1
  fi
  local _info="${__bashfs_offset[$1]}"
  if [ -z "$_info" ]; then
    echo "bashfs: file not found: $1" >&2
    return 1
  fi
  local _off="${_info%%:*}"
  local _len="${_info##*:}"
  mkdir -p "$(dirname "$2")" && tail -c "+$(($(__bashfs_payload_start) + _off))" "${BASH_SOURCE[0]}" | head -c "$_len" | __DECODE__ > "$2"
}

`

func writeExtractFns(b *strings.Builder, decode string) {
	b.WriteString(strings.ReplaceAll(extractTemplate, "__DECODE__", decode))
}

// writeListAndJq emits the list and jq helpers, identical across encoding modes.
func writeListAndJq(b *strings.Builder, infos []fileInfo) {
	b.WriteString("bashfs_list() {\n")
	for _, info := range infos {
		fmt.Fprintf(b, "  echo '%s'\n", info.relPath)
	}
	b.WriteString("}\n")

	b.WriteString("\nbashfs_jq() { bashfs_cat \"$1\" | jq \"${2:-.}\"; }\n")
}
