package bashgen

import (
	"fmt"
	"os"
	"strings"

	"bashfs/internal/embed"
	"bashfs/internal/fswalker"
)

// EmbeddedResult holds the generated bash code and the trailing payload that
// gets appended to the script after the exit guard. For raw mode the payload
// is concatenated gzip bytes; for base64 mode it is a concatenation of
// per-file base64-encoded gzip chunks (still []byte, but printable ASCII).
type EmbeddedResult struct {
	Script  string
	Payload []byte
}

type fileInfo struct {
	relPath string
	offset  int
	length  int
}

// chunkFn turns a single file's raw contents into the bytes that get appended
// to the trailing payload. For raw mode it's just gzip; for base64 mode it's
// gzip + per-blob base64.
type chunkFn func(data []byte) ([]byte, error)

// collectChunks reads each file, transforms it via fn, and accumulates the
// transformed bytes into a single payload while tracking offsets/lengths into
// that payload.
func collectChunks(files []fswalker.FileEntry, fn chunkFn) ([]byte, []fileInfo, error) {
	var payload []byte
	var infos []fileInfo
	for _, f := range files {
		data, err := os.ReadFile(f.AbsPath)
		if err != nil {
			return nil, nil, fmt.Errorf("reading %s: %w", f.AbsPath, err)
		}
		chunk, err := fn(data)
		if err != nil {
			return nil, nil, fmt.Errorf("encoding %s: %w", f.RelPath, err)
		}
		infos = append(infos, fileInfo{
			relPath: f.RelPath,
			offset:  len(payload),
			length:  len(chunk),
		})
		payload = append(payload, chunk...)
	}
	return payload, infos, nil
}

// writePreamble emits the header comment, payload size, offset map, and
// __bashfs_payload_start helper. Same shape for raw and base64 modes — the
// payload size is the byte length of whatever ends up at the end of the file.
func writePreamble(b *strings.Builder, modeLabel string, payloadSize int, infos []fileInfo) {
	fmt.Fprintf(b, "# Generated by bashfs (%s mode) - DO NOT EDIT\n\n", modeLabel)

	// Total payload size lets the helpers compute the payload offset from
	// filesize at runtime, so the script is self-relocating: layout changes
	// (e.g. the curl|bash trampoline writing to a tempfile) don't need a
	// patched-in absolute offset.
	fmt.Fprintf(b, "__bashfs_payload_size=%d\n\n", payloadSize)

	b.WriteString("declare -A __bashfs_offset=(\n")
	for _, info := range infos {
		fmt.Fprintf(b, "  [\"%s\"]=\"%d:%d\"\n", info.relPath, info.offset, info.length)
	}
	b.WriteString(")\n\n")

	b.WriteString(`__bashfs_payload_start() {
  echo $(( $(wc -c < "${BASH_SOURCE[0]}") - __bashfs_payload_size + 1 ))
}

`)
}

// writeListAndJq emits the list and jq helpers, which are identical across
// encoding modes.
func writeListAndJq(b *strings.Builder, infos []fileInfo) {
	b.WriteString("bashfs_list() {\n")
	for _, info := range infos {
		fmt.Fprintf(b, "  echo '%s'\n", info.relPath)
	}
	b.WriteString("}\n")

	b.WriteString("\nbashfs_jq() { bashfs_cat \"$1\" | jq \"${2:-.}\"; }\n")
}

// GenerateEmbedded produces bash code that reads compressed file data from the
// end of the script itself (after an exit 0 guard). File contents are stored as
// a raw binary payload appended to the script; the bash code uses tail/head to
// extract individual files by byte offset and length.
func GenerateEmbedded(files []fswalker.FileEntry) (*EmbeddedResult, error) {
	payload, infos, err := collectChunks(files, embed.Compress)
	if err != nil {
		return nil, err
	}

	var b strings.Builder
	writePreamble(&b, "embedded", len(payload), infos)

	b.WriteString(`bashfs_cat() {
  local _info="${__bashfs_offset[$1]}"
  if [ -z "$_info" ]; then
    echo "bashfs: file not found: $1" >&2
    return 1
  fi
  local _off="${_info%%:*}"
  local _len="${_info##*:}"
  tail -c "+$(($(__bashfs_payload_start) + _off))" "${BASH_SOURCE[0]}" | head -c "$_len" | gzip -d
}

bashfs_extract() {
  local _info="${__bashfs_offset[$1]}"
  if [ -z "$_info" ]; then
    echo "bashfs: file not found: $1" >&2
    return 1
  fi
  local _off="${_info%%:*}"
  local _len="${_info##*:}"
  mkdir -p "$(dirname "$2")" && tail -c "+$(($(__bashfs_payload_start) + _off))" "${BASH_SOURCE[0]}" | head -c "$_len" | gzip -d > "$2"
}

`)

	writeListAndJq(&b, infos)

	return &EmbeddedResult{
		Script:  b.String(),
		Payload: payload,
	}, nil
}

// GenerateEmbeddedBase64 is the copy-paste-safe variant: each file is gzipped
// then base64-encoded individually, and the per-file base64 chunks are
// concatenated as the trailing payload. Offsets in the map index the base64
// byte stream, so the runtime can slice a single file's chunk and decode just
// that chunk — no need to base64-decode the whole payload to extract one file.
//
// Per-file (rather than whole-payload) base64 encoding is what makes slicing
// safe: each chunk has its own padding and starts at a 4-byte boundary in the
// concatenated stream, so any sliced range is valid base64 standing alone.
func GenerateEmbeddedBase64(files []fswalker.FileEntry) (*EmbeddedResult, error) {
	payload, infos, err := collectChunks(files, func(data []byte) ([]byte, error) {
		s, err := embed.Encode(data)
		if err != nil {
			return nil, err
		}
		return []byte(s), nil
	})
	if err != nil {
		return nil, err
	}

	var b strings.Builder
	writePreamble(&b, "base64", len(payload), infos)

	b.WriteString(`bashfs_cat() {
  local _info="${__bashfs_offset[$1]}"
  if [ -z "$_info" ]; then
    echo "bashfs: file not found: $1" >&2
    return 1
  fi
  local _off="${_info%%:*}"
  local _len="${_info##*:}"
  tail -c "+$(($(__bashfs_payload_start) + _off))" "${BASH_SOURCE[0]}" | head -c "$_len" | base64 -d | gzip -d
}

bashfs_extract() {
  local _info="${__bashfs_offset[$1]}"
  if [ -z "$_info" ]; then
    echo "bashfs: file not found: $1" >&2
    return 1
  fi
  local _off="${_info%%:*}"
  local _len="${_info##*:}"
  mkdir -p "$(dirname "$2")" && tail -c "+$(($(__bashfs_payload_start) + _off))" "${BASH_SOURCE[0]}" | head -c "$_len" | base64 -d | gzip -d > "$2"
}

`)

	writeListAndJq(&b, infos)

	return &EmbeddedResult{
		Script:  b.String(),
		Payload: payload,
	}, nil
}
