package bashgen

import (
	"fmt"
	"os"
	"strings"
	"text/template"

	"bashfs/internal/embed"
	"bashfs/internal/fswalker"
)

// EmbeddedResult holds the generated bash code and the trailing payload that
// gets appended to the script after the exit guard. For raw mode the payload
// is concatenated gzip bytes; for base64 mode it is a concatenation of
// per-file base64-encoded gzip chunks (still []byte, but printable ASCII).
type EmbeddedResult struct {
	Script  string
	Payload []byte
}

type fileInfo struct {
	RelPath string
	Offset  int
	Length  int
}

// chunkFn turns a single file's raw contents into the bytes that get appended
// to the trailing payload.
type chunkFn func(data []byte) ([]byte, error)

// encodingSpec is everything that differs between raw and base64 modes. The
// generator pipeline is otherwise shared verbatim.
type encodingSpec struct {
	label  string  // appears in the header comment
	chunk  chunkFn // per-file payload transform
	decode string  // bash decode pipeline tacked on after `head -c "$_len" |`
}

var rawSpec = encodingSpec{
	label:  "embedded",
	chunk:  embed.Compress,
	decode: "gzip -d",
}

var base64Spec = encodingSpec{
	label: "base64",
	chunk: func(data []byte) ([]byte, error) {
		s, err := embed.Encode(data)
		if err != nil {
			return nil, err
		}
		return []byte(s), nil
	},
	decode: "base64 -d | gzip -d",
}

type scriptData struct {
	Label       string
	PayloadSize int
	Files       []fileInfo
	Decode      string
}

var scriptTmpl = template.Must(template.New("script").Parse(scriptTemplate))

const scriptTemplate = `# Generated by bashfs ({{.Label}} mode) - DO NOT EDIT

__bashfs_payload_size={{.PayloadSize}}

declare -A __bashfs_offset=(
{{- range .Files}}
  ["{{.RelPath}}"]="{{.Offset}}:{{.Length}}"
{{- end}}
)

__bashfs_payload_start() {
  echo $(( $(wc -c < "${BASH_SOURCE[0]}") - __bashfs_payload_size + 1 ))
}

bashfs_cat() {
  local _info="${__bashfs_offset[$1]}"
  if [ -z "$_info" ]; then
    echo "bashfs: file not found: $1" >&2
    return 1
  fi
  local _off="${_info%%:*}"
  local _len="${_info##*:}"
  tail -c "+$(($(__bashfs_payload_start) + _off))" "${BASH_SOURCE[0]}" | head -c "$_len" | {{.Decode}}
}

bashfs_extract() {
  mkdir -p "$(dirname "$2")" && bashfs_cat "$1" > "$2"
}

bashfs_list() {
  local _k; for _k in "${!__bashfs_offset[@]}"; do printf '%s\n' "$_k"; done | sort
}

bashfs_jq() { bashfs_cat "$1" | jq "${2:-.}"; }
`

// GenerateEmbedded produces bash code that reads compressed file data from the
// end of the script itself (after an exit 0 guard). File contents are stored as
// a raw binary payload appended to the script; the bash code uses tail/head to
// extract individual files by byte offset and length.
func GenerateEmbedded(files []fswalker.FileEntry) (*EmbeddedResult, error) {
	return generate(files, rawSpec)
}

// GenerateEmbeddedBase64 is the copy-paste-safe variant: each file is gzipped
// then base64-encoded individually, and the per-file base64 chunks are
// concatenated as the trailing payload. Offsets in the map index the base64
// byte stream, so the runtime can slice a single file's chunk and decode just
// that chunk - no need to base64-decode the whole payload to extract one file.
//
// Per-file (rather than whole-payload) base64 encoding is what makes slicing
// safe: each chunk has its own padding and starts at a 4-byte boundary in the
// concatenated stream, so any sliced range is valid base64 standing alone.
func GenerateEmbeddedBase64(files []fswalker.FileEntry) (*EmbeddedResult, error) {
	return generate(files, base64Spec)
}

func generate(files []fswalker.FileEntry, spec encodingSpec) (*EmbeddedResult, error) {
	payload, infos, err := collectChunks(files, spec.chunk)
	if err != nil {
		return nil, err
	}

	var b strings.Builder
	err = scriptTmpl.Execute(&b, scriptData{
		Label:       spec.label,
		PayloadSize: len(payload),
		Files:       infos,
		Decode:      spec.decode,
	})
	if err != nil {
		return nil, fmt.Errorf("executing template: %w", err)
	}

	return &EmbeddedResult{
		Script:  b.String(),
		Payload: payload,
	}, nil
}

// collectChunks reads each file, transforms it via fn, and accumulates the
// transformed bytes into a single payload while tracking offsets/lengths into
// that payload.
func collectChunks(files []fswalker.FileEntry, fn chunkFn) ([]byte, []fileInfo, error) {
	var payload []byte
	var infos []fileInfo
	for _, f := range files {
		data, err := os.ReadFile(f.AbsPath)
		if err != nil {
			return nil, nil, fmt.Errorf("reading %s: %w", f.AbsPath, err)
		}
		chunk, err := fn(data)
		if err != nil {
			return nil, nil, fmt.Errorf("encoding %s: %w", f.RelPath, err)
		}
		infos = append(infos, fileInfo{
			RelPath: f.RelPath,
			Offset:  len(payload),
			Length:  len(chunk),
		})
		payload = append(payload, chunk...)
	}
	return payload, infos, nil
}
